##############################################################################
# Sonata Core
##############################################################################
sonata_core:
    flashmessage:
        error:
            css_class: danger
            types:
                - {type: sonata_core_error, domain: "SonataCoreBundle" }
        warning:
            css_class: warning
            types:
                - {type: sonata_core_warning, domain: "SonataCoreBundle" }
        info:
            css_class: info
            types:
                - {type: sonata_core_info, domain: "SonataCoreBundle" }
        success:
            css_class: success
            types:
                - {type: sonata_core_success, domain: "SonataCoreBundle" }
